#!/usr/bin/env python3
"""
PDF Report Generator for Botwave Janitor Squad
Professional report generation with charts, branding, and multiple templates
"""

import os
import io
import uuid
import sqlite3
from datetime import datetime, timedelta
from pathlib import Path
from typing import Dict, Any, List, Optional, Tuple
from dataclasses import dataclass, asdict
from enum import Enum

from fpdf import FPDF
import matplotlib
matplotlib.use('Agg')  # Non-interactive backend
import matplotlib.pyplot as plt
import numpy as np

# Botwave branding colors
BOTWAVE_COLORS = {
    'primary': '#1a1a2e',      # Dark blue
    'secondary': '#16213e',    # Navy blue
    'accent': '#3b82f6',       # Botwave blue
    'success': '#10b981',      # Green
    'warning': '#f59e0b',      # Orange
    'danger': '#ef4444',       # Red
    'light': '#ffffff',        # White
    'gray': '#888888',         # Gray
    'dark': '#0f0f0f',         # Dark background
}


class ReportType(Enum):
    """Types of reports available."""
    SERVICE = "service"
    ANALYTICS = "analytics"
    AUDIT = "audit"


@dataclass
class ReportMetadata:
    """Metadata for a generated report."""
    report_id: str
    report_type: str
    customer_id: Optional[str]
    title: str
    generated_at: str
    file_path: str
    file_size: int
    status: str = "completed"


class BotwavePDF(FPDF):
    """Custom PDF class with Botwave branding."""
    
    def __init__(self, title: str = "Botwave Report", subtitle: str = ""):
        super().__init__()
        self.report_title = title
        self.report_subtitle = subtitle
        self.report_date = datetime.now().strftime("%B %d, %Y")
        self.set_auto_page_break(auto=True, margin=20)
        
    def header(self):
        """Add branded header to each page."""
        # Background gradient effect (simulated with filled rectangles)
        self.set_fill_color(26, 26, 46)  # #1a1a2e
        self.rect(0, 0, self.w, 35, 'F')
        
        # Botwave logo/text
        self.set_font('Helvetica', 'B', 20)
        self.set_text_color(255, 255, 255)
        self.set_xy(15, 10)
        self.cell(0, 10, 'BOTWAVE', ln=False)
        
        # Report title
        self.set_font('Helvetica', '', 12)
        self.set_text_color(59, 130, 246)  # #3b82f6
        self.set_xy(15, 20)
        self.cell(0, 10, self.report_title, ln=True)
        
        # Date on right side
        self.set_font('Helvetica', '', 10)
        self.set_text_color(136, 136, 136)  # #888888
        self.set_xy(-60, 10)
        self.cell(0, 10, self.report_date, ln=True)
        
        # Accent line
        self.set_fill_color(59, 130, 246)  # #3b82f6
        self.rect(0, 35, self.w, 2, 'F')
        
        # Move cursor down
        self.ln(20)
        
    def footer(self):
        """Add branded footer to each page."""
        self.set_y(-20)
        
        # Footer background
        self.set_fill_color(15, 15, 15)  # #0f0f0f
        self.rect(0, self.h - 20, self.w, 20, 'F')
        
        # Page number
        self.set_font('Helvetica', '', 10)
        self.set_text_color(136, 136, 136)
        self.cell(0, 10, f'Page {self.page_no()}', 0, 0, 'C')
        
        # Botwave branding
        self.set_x(-60)
        self.set_font('Helvetica', 'B', 8)
        self.set_text_color(59, 130, 246)
        self.cell(0, 10, 'Generated by Botwave', 0, 0, 'R')
        
    def chapter_title(self, title: str):
        """Add a styled chapter title."""
        self.set_font('Helvetica', 'B', 16)
        self.set_text_color(26, 26, 46)
        self.cell(0, 10, title, ln=True, align='L')
        
        # Underline
        self.set_fill_color(59, 130, 246)
        self.rect(self.get_x(), self.get_y(), 40, 2, 'F')
        self.ln(8)
        
    def chapter_body(self, body: str):
        """Add body text."""
        self.set_font('Helvetica', '', 11)
        self.set_text_color(60, 60, 60)
        self.multi_cell(0, 6, body)
        self.ln()
        
    def add_metric_card(self, label: str, value: str, color: str = 'accent'):
        """Add a metric card."""
        # Parse hex color
        hex_color = BOTWAVE_COLORS.get(color, BOTWAVE_COLORS['accent'])
        r = int(hex_color[1:3], 16)
        g = int(hex_color[3:5], 16)
        b = int(hex_color[5:7], 16)
        
        # Card background
        self.set_fill_color(245, 245, 250)
        self.set_draw_color(r, g, b)
        self.set_line_width(0.5)
        
        card_w = 85
        card_h = 30
        x = self.get_x()
        y = self.get_y()
        
        self.rect(x, y, card_w, card_h, 'DF')
        
        # Label
        self.set_xy(x + 5, y + 5)
        self.set_font('Helvetica', '', 9)
        self.set_text_color(136, 136, 136)
        self.cell(0, 5, label.upper(), ln=True)
        
        # Value
        self.set_xy(x + 5, y + 14)
        self.set_font('Helvetica', 'B', 18)
        self.set_text_color(r, g, b)
        self.cell(0, 10, value, ln=True)
        
        # Move position
        self.set_xy(x + card_w + 10, y)
        
    def add_table(self, headers: List[str], data: List[List[str]], col_widths: Optional[List[int]] = None):
        """Add a styled table."""
        if not col_widths:
            col_widths = [40] * len(headers)
            
        # Header
        self.set_fill_color(26, 26, 46)
        self.set_text_color(255, 255, 255)
        self.set_font('Helvetica', 'B', 10)
        self.set_line_width(0.3)
        
        for i, header in enumerate(headers):
            self.cell(col_widths[i], 10, header, 1, 0, 'C', True)
        self.ln()
        
        # Data rows
        self.set_text_color(60, 60, 60)
        self.set_font('Helvetica', '', 9)
        
        for row in data:
            for i, cell in enumerate(row):
                self.cell(col_widths[i], 8, str(cell), 1, 0, 'L')
            self.ln()
            
        self.ln(5)


class ReportGenerator:
    """Main report generator class."""
    
    def __init__(self, output_dir: Optional[Path] = None):
        self.output_dir = output_dir or Path("data/reports")
        self.output_dir.mkdir(parents=True, exist_ok=True)
        self._init_database()
        
    def _init_database(self):
        """Initialize report tracking database."""
        self.db_path = self.output_dir / "reports.db"
        with sqlite3.connect(self.db_path) as conn:
            conn.execute("""
                CREATE TABLE IF NOT EXISTS reports (
                    id TEXT PRIMARY KEY,
                    report_type TEXT NOT NULL,
                    customer_id TEXT,
                    title TEXT NOT NULL,
                    generated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    file_path TEXT NOT NULL,
                    file_size INTEGER DEFAULT 0,
                    status TEXT DEFAULT 'completed'
                )
            """)
            
    def _hex_to_rgb(self, hex_color: str) -> Tuple[int, int, int]:
        """Convert hex color to RGB tuple."""
        hex_color = hex_color.lstrip('#')
        return tuple(int(hex_color[i:i+2], 16) for i in (0, 2, 4))
        
    def _create_chart(self, chart_type: str, data: Dict[str, Any], 
                     width: int = 8, height: int = 4, dpi: int = 100) -> Path:
        """Create a matplotlib chart and save to file."""
        fig, ax = plt.subplots(figsize=(width, height), dpi=dpi)
        
        # Botwave color scheme
        colors = ['#3b82f6', '#10b981', '#f59e0b', '#ef4444', '#8b5cf6']
        
        if chart_type == 'bar':
            labels = data.get('labels', [])
            values = data.get('values', [])
            bars = ax.bar(labels, values, color=colors[:len(values)])
            ax.set_ylabel(data.get('ylabel', 'Value'))
            ax.set_title(data.get('title', ''), color='white', fontweight='bold')
            
        elif chart_type == 'line':
            x = data.get('x', [])
            y = data.get('y', [])
            ax.plot(x, y, color='#3b82f6', linewidth=2, marker='o')
            ax.set_ylabel(data.get('ylabel', 'Value'))
            ax.set_title(data.get('title', ''), color='white', fontweight='bold')
            ax.grid(True, alpha=0.3)
            
        elif chart_type == 'pie':
            labels = data.get('labels', [])
            values = data.get('values', [])
            ax.pie(values, labels=labels, colors=colors, autopct='%1.1f%%',
                   textprops={'color': 'white', 'fontsize': 10})
            ax.set_title(data.get('title', ''), color='white', fontweight='bold')
            
        # Style for dark theme
        fig.patch.set_facecolor('#1a1a2e')
        ax.set_facecolor('#1a1a2e')
        ax.tick_params(colors='white')
        ax.xaxis.label.set_color('white')
        ax.yaxis.label.set_color('white')
        ax.title.set_color('white')
        for spine in ax.spines.values():
            spine.set_color('#333333')
            
        # Save chart
        chart_path = self.output_dir / f"chart_{uuid.uuid4().hex[:8]}.png"
        plt.tight_layout()
        plt.savefig(chart_path, facecolor='#1a1a2e', bbox_inches='tight')
        plt.close()
        
        return chart_path
        
    def generate_service_report(self, data: Dict[str, Any]) -> ReportMetadata:
        """Generate a service completion report."""
        report_id = f"SRV_{uuid.uuid4().hex[:12].upper()}"
        customer_name = data.get('customer_name', 'Unknown Customer')
        service_date = data.get('service_date', datetime.now().strftime('%Y-%m-%d'))
        
        pdf = BotwavePDF(
            title="Service Report",
            subtitle=f"For {customer_name}"
        )
        pdf.add_page()
        
        # Service Summary Section
        pdf.chapter_title("Service Summary")
        
        # Service details box
        pdf.set_fill_color(245, 245, 250)
        pdf.rect(15, pdf.get_y(), 180, 50, 'F')
        
        pdf.set_xy(20, pdf.get_y() + 5)
        pdf.set_font('Helvetica', 'B', 11)
        pdf.set_text_color(26, 26, 46)
        pdf.cell(0, 6, f"Customer: {customer_name}", ln=True)
        
        pdf.set_x(20)
        pdf.cell(0, 6, f"Service Date: {service_date}", ln=True)
        
        pdf.set_x(20)
        pdf.cell(0, 6, f"Service Type: {data.get('service_type', 'General Service')}", ln=True)
        
        pdf.set_x(20)
        pdf.cell(0, 6, f"Technician: {data.get('technician', 'Botwave Agent')}", ln=True)
        
        pdf.set_x(20)
        pdf.cell(0, 6, f"Report ID: {report_id}", ln=True)
        
        pdf.ln(15)
        
        # Service Details
        pdf.chapter_title("Service Details")
        pdf.chapter_body(data.get('service_description', 'Service completed successfully.'))
        
        # Work Performed
        pdf.chapter_title("Work Performed")
        work_items = data.get('work_items', [])
        if work_items:
            for i, item in enumerate(work_items, 1):
                pdf.set_font('Helvetica', '', 11)
                pdf.set_text_color(60, 60, 60)
                pdf.cell(0, 6, f"  {i}. {item}", ln=True)
        else:
            pdf.chapter_body("Standard service procedures completed.")
        pdf.ln(5)
        
        # Materials Used
        materials = data.get('materials', [])
        if materials:
            pdf.chapter_title("Materials & Parts")
            headers = ['Item', 'Quantity', 'Unit Price', 'Total']
            table_data = []
            total = 0
            for m in materials:
                item_total = m.get('quantity', 0) * m.get('unit_price', 0)
                table_data.append([
                    m.get('name', ''),
                    str(m.get('quantity', 0)),
                    f"${m.get('unit_price', 0):.2f}",
                    f"${item_total:.2f}"
                ])
                total += item_total
            table_data.append(['', '', 'TOTAL:', f"${total:.2f}"])
            pdf.add_table(headers, table_data, [80, 25, 35, 35])
        
        # Cost Summary
        pdf.chapter_title("Cost Summary")
        labor_cost = data.get('labor_cost', 0)
        materials_cost = data.get('materials_cost', 0)
        tax = data.get('tax', (labor_cost + materials_cost) * 0.08)
        total = labor_cost + materials_cost + tax
        
        summary_data = [
            ['Labor:', f"${labor_cost:.2f}"],
            ['Materials:', f"${materials_cost:.2f}"],
            ['Tax (8%):', f"${tax:.2f}"],
            ['TOTAL:', f"${total:.2f}"]
        ]
        pdf.set_font('Helvetica', 'B', 12)
        for label, value in summary_data:
            pdf.cell(100, 8, label, 0, 0, 'R')
            pdf.cell(40, 8, value, 0, 1, 'R')
        
        # Add signature section
        pdf.ln(20)
        pdf.set_font('Helvetica', '', 10)
        pdf.set_text_color(100, 100, 100)
        pdf.cell(90, 10, "_________________________", 0, 0, 'C')
        pdf.cell(90, 10, "_________________________", 0, 1, 'C')
        pdf.cell(90, 5, "Technician Signature", 0, 0, 'C')
        pdf.cell(90, 5, "Customer Signature", 0, 1, 'C')
        
        # Save report
        filename = f"{report_id}_{customer_name.replace(' ', '_')}.pdf"
        file_path = self.output_dir / filename
        pdf.output(str(file_path))
        
        return self._save_report_metadata(report_id, ReportType.SERVICE, 
                                          data.get('customer_id'), 
                                          f"Service Report - {customer_name}", 
                                          file_path)
        
    def generate_analytics_report(self, data: Dict[str, Any]) -> ReportMetadata:
        """Generate an analytics/monthly statistics report."""
        report_id = f"ANL_{uuid.uuid4().hex[:12].upper()}"
        period = data.get('period', 'Monthly')
        business_name = data.get('business_name', 'Botwave Services')
        
        pdf = BotwavePDF(
            title=f"{period} Analytics Report",
            subtitle=business_name
        )
        pdf.add_page()
        
        # Executive Summary
        pdf.chapter_title("Executive Summary")
        summary = data.get('summary', f"This report covers analytics for {period}.")
        pdf.chapter_body(summary)
        
        # Key Metrics
        pdf.chapter_title("Key Performance Metrics")
        
        metrics = data.get('metrics', {})
        revenue = metrics.get('revenue', 0)
        jobs_completed = metrics.get('jobs_completed', 0)
        avg_response_time = metrics.get('avg_response_time', 'N/A')
        customer_satisfaction = metrics.get('customer_satisfaction', 0)
        
        # Display metrics in grid
        start_y = pdf.get_y()
        pdf.set_xy(15, start_y)
        pdf.add_metric_card("Total Revenue", f"${revenue:,.2f}", 'accent')
        pdf.add_metric_card("Jobs Completed", str(jobs_completed), 'success')
        pdf.ln(35)
        pdf.set_xy(15, pdf.get_y())
        pdf.add_metric_card("Avg Response", str(avg_response_time), 'warning')
        pdf.add_metric_card("Satisfaction", f"{customer_satisfaction}%", 'success' if customer_satisfaction >= 80 else 'warning')
        pdf.ln(20)
        
        # Charts section
        charts_data = data.get('charts', [])
        if charts_data:
            pdf.chapter_title("Performance Visualization")
            
            for chart in charts_data:
                chart_type = chart.get('type', 'bar')
                chart_path = self._create_chart(chart_type, chart)
                
                pdf.image(str(chart_path), x=15, w=180)
                pdf.ln(5)
                
                # Clean up temp chart file
                chart_path.unlink(missing_ok=True)
        
        # Detailed breakdown
        pdf.add_page()
        pdf.chapter_title("Service Breakdown by Category")
        
        categories = data.get('categories', [])
        if categories:
            headers = ['Category', 'Jobs', 'Revenue', 'Avg Job Value']
            table_data = []
            for cat in categories:
                table_data.append([
                    cat.get('name', ''),
                    str(cat.get('jobs', 0)),
                    f"${cat.get('revenue', 0):,.2f}",
                    f"${cat.get('avg_value', 0):.2f}"
                ])
            pdf.add_table(headers, table_data, [60, 30, 50, 40])
        
        # Customer insights
        pdf.chapter_title("Customer Insights")
        new_customers = data.get('new_customers', 0)
        returning_customers = data.get('returning_customers', 0)
        total_customers = new_customers + returning_customers
        
        pdf.chapter_body(f"""
During this reporting period:

  • New customers acquired: {new_customers}
  • Returning customers: {returning_customers}
  • Total unique customers served: {total_customers}
  • Customer retention rate: {(returning_customers/total_customers*100 if total_customers > 0 else 0):.1f}%
        """)
        
        # Save report
        filename = f"{report_id}_{period.replace(' ', '_')}_Analytics.pdf"
        file_path = self.output_dir / filename
        pdf.output(str(file_path))
        
        return self._save_report_metadata(report_id, ReportType.ANALYTICS,
                                          data.get('customer_id'),
                                          f"{period} Analytics Report - {business_name}",
                                          file_path)
        
    def generate_audit_report(self, data: Dict[str, Any]) -> ReportMetadata:
        """Generate a compliance/business audit report."""
        report_id = f"AUD_{uuid.uuid4().hex[:12].upper()}"
        audit_type = data.get('audit_type', 'Compliance')
        audit_date = data.get('audit_date', datetime.now().strftime('%Y-%m-%d'))
        
        pdf = BotwavePDF(
            title=f"{audit_type} Audit Report",
            subtitle=f"Conducted on {audit_date}"
        )
        pdf.add_page()
        
        # Audit Overview
        pdf.chapter_title("Audit Overview")
        pdf.chapter_body(data.get('overview', f'This {audit_type} audit was conducted to ensure compliance with business standards and regulations.'))
        
        # Audit Scope
        pdf.chapter_title("Audit Scope")
        scope_items = data.get('scope', ['General operations', 'Financial records', 'Compliance standards'])
        for item in scope_items:
            pdf.set_font('Helvetica', '', 11)
            pdf.set_text_color(60, 60, 60)
            pdf.cell(0, 6, f"  • {item}", ln=True)
        pdf.ln(5)
        
        # Findings
        pdf.chapter_title("Key Findings")
        findings = data.get('findings', [])
        
        if findings:
            headers = ['Area', 'Status', 'Severity', 'Description']
            table_data = []
            for finding in findings:
                table_data.append([
                    finding.get('area', ''),
                    finding.get('status', ''),
                    finding.get('severity', ''),
                    finding.get('description', '')[:50] + '...'
                ])
            pdf.add_table(headers, table_data, [40, 30, 25, 85])
        else:
            pdf.chapter_body("No significant findings reported. All areas reviewed met required standards.")
        
        # Compliance Status
        pdf.chapter_title("Compliance Status")
        compliance_score = data.get('compliance_score', 100)
        
        # Progress bar visualization
        pdf.set_fill_color(240, 240, 240)
        pdf.rect(15, pdf.get_y(), 180, 20, 'F')
        
        # Score bar
        score_color = 'success' if compliance_score >= 90 else 'warning' if compliance_score >= 70 else 'danger'
        r, g, b = self._hex_to_rgb(BOTWAVE_COLORS[score_color])
        pdf.set_fill_color(r, g, b)
        pdf.rect(15, pdf.get_y(), 180 * (compliance_score / 100), 20, 'F')
        
        # Score text
        pdf.set_xy(15, pdf.get_y() + 5)
        pdf.set_font('Helvetica', 'B', 14)
        pdf.set_text_color(255, 255, 255)
        pdf.cell(0, 10, f"Compliance Score: {compliance_score}%", 0, 1, 'C')
        pdf.ln(10)
        
        # Recommendations
        pdf.chapter_title("Recommendations")
        recommendations = data.get('recommendations', [])
        if recommendations:
            for i, rec in enumerate(recommendations, 1):
                priority = rec.get('priority', 'Medium')
                priority_color = {'High': 'danger', 'Medium': 'warning', 'Low': 'success'}.get(priority, 'accent')
                r, g, b = self._hex_to_rgb(BOTWAVE_COLORS[priority_color])
                
                # Priority badge
                pdf.set_fill_color(r, g, b)
                pdf.set_text_color(255, 255, 255)
                pdf.set_font('Helvetica', 'B', 8)
                pdf.cell(20, 6, priority.upper(), 0, 0, 'C', True)
                
                # Recommendation text
                pdf.set_text_color(60, 60, 60)
                pdf.set_font('Helvetica', '', 11)
                pdf.cell(5, 6, '', 0, 0)
                pdf.cell(0, 6, rec.get('text', ''), 0, 1)
                pdf.ln(3)
        else:
            pdf.chapter_body("No recommendations at this time. Continue current practices.")
        
        pdf.ln(10)
        
        # Auditor signature
        pdf.set_font('Helvetica', 'B', 11)
        pdf.set_text_color(26, 26, 46)
        pdf.cell(0, 10, "Audit Conducted By:", ln=True)
        pdf.set_font('Helvetica', '', 11)
        pdf.set_text_color(60, 60, 60)
        pdf.cell(0, 6, f"  {data.get('auditor', 'Botwave Audit System')}", ln=True)
        pdf.cell(0, 6, f"  Date: {audit_date}", ln=True)
        
        # Save report
        filename = f"{report_id}_{audit_type.replace(' ', '_')}_Audit.pdf"
        file_path = self.output_dir / filename
        pdf.output(str(file_path))
        
        return self._save_report_metadata(report_id, ReportType.AUDIT,
                                          data.get('customer_id'),
                                          f"{audit_type} Audit - {audit_date}",
                                          file_path)
        
    def _save_report_metadata(self, report_id: str, report_type: ReportType,
                              customer_id: Optional[str], title: str,
                              file_path: Path) -> ReportMetadata:
        """Save report metadata to database."""
        file_size = file_path.stat().st_size
        
        with sqlite3.connect(self.db_path) as conn:
            conn.execute("""
                INSERT INTO reports (id, report_type, customer_id, title, file_path, file_size)
                VALUES (?, ?, ?, ?, ?, ?)
            """, (report_id, report_type.value, customer_id, title, str(file_path), file_size))
            
        return ReportMetadata(
            report_id=report_id,
            report_type=report_type.value,
            customer_id=customer_id,
            title=title,
            generated_at=datetime.now().isoformat(),
            file_path=str(file_path),
            file_size=file_size
        )
        
    def list_reports(self, customer_id: Optional[str] = None,
                    report_type: Optional[str] = None) -> List[Dict[str, Any]]:
        """List all reports, optionally filtered."""
        query = "SELECT * FROM reports WHERE 1=1"
        params = []
        
        if customer_id:
            query += " AND customer_id = ?"
            params.append(customer_id)
        if report_type:
            query += " AND report_type = ?"
            params.append(report_type)
            
        query += " ORDER BY generated_at DESC"
        
        with sqlite3.connect(self.db_path) as conn:
            conn.row_factory = sqlite3.Row
            rows = conn.execute(query, params).fetchall()
            return [dict(row) for row in rows]
            
    def get_report(self, report_id: str) -> Optional[Dict[str, Any]]:
        """Get a specific report by ID."""
        with sqlite3.connect(self.db_path) as conn:
            conn.row_factory = sqlite3.Row
            row = conn.execute(
                "SELECT * FROM reports WHERE id = ?",
                (report_id,)
            ).fetchone()
            return dict(row) if row else None
            
    def delete_report(self, report_id: str) -> bool:
        """Delete a report and its file."""
        report = self.get_report(report_id)
        if not report:
            return False
            
        # Delete file
        try:
            Path(report['file_path']).unlink(missing_ok=True)
        except Exception:
            pass
            
        # Delete from database
        with sqlite3.connect(self.db_path) as conn:
            conn.execute("DELETE FROM reports WHERE id = ?", (report_id,))
            
        return True


# Global instance
report_generator = ReportGenerator()


if __name__ == "__main__":
    # Demo: Generate sample reports
    print("Generating sample reports...")
    
    # Service Report Demo
    service_data = {
        'customer_name': 'Acme Plumbing Co.',
        'customer_id': 'CUST_001',
        'service_date': '2024-03-15',
        'service_type': 'System Cleanup',
        'technician': 'Janitor Squad Alpha',
        'service_description': 'Completed comprehensive system cleanup and optimization for customer infrastructure.',
        'work_items': [
            'Database optimization and cleanup',
            'Log file archival and rotation',
            'Temporary file removal',
            'Security scan and patch application'
        ],
        'materials': [
            {'name': 'Storage Cleanup', 'quantity': 1, 'unit_price': 150.00},
            {'name': 'Security Patch', 'quantity': 2, 'unit_price': 75.00}
        ],
        'labor_cost': 450.00,
        'materials_cost': 300.00,
        'tax': 60.00
    }
    
    result = report_generator.generate_service_report(service_data)
    print(f"Service report generated: {result.report_id}")
    
    # Analytics Report Demo
    analytics_data = {
        'business_name': 'Jimenez Plumbing Services',
        'period': 'March 2024',
        'metrics': {
            'revenue': 24750.00,
            'jobs_completed': 47,
            'avg_response_time': '2.3 hours',
            'customer_satisfaction': 94
        },
        'charts': [
            {
                'type': 'bar',
                'labels': ['Week 1', 'Week 2', 'Week 3', 'Week 4'],
                'values': [5800, 6200, 5900, 6850],
                'ylabel': 'Revenue ($)',
                'title': 'Weekly Revenue Trend'
            }
        ],
        'categories': [
            {'name': 'Leak Repairs', 'jobs': 18, 'revenue': 7200, 'avg_value': 400},
            {'name': 'Installations', 'jobs': 12, 'revenue': 8400, 'avg_value': 700},
            {'name': 'Maintenance', 'jobs': 17, 'revenue': 9150, 'avg_value': 538}
        ],
        'new_customers': 23,
        'returning_customers': 24
    }
    
    result = report_generator.generate_analytics_report(analytics_data)
    print(f"Analytics report generated: {result.report_id}")
    
    # Audit Report Demo
    audit_data = {
        'audit_type': 'Security Compliance',
        'audit_date': '2024-03-30',
        'auditor': 'Botwave Security Team',
        'overview': 'Comprehensive security compliance audit covering data protection, access controls, and regulatory requirements.',
        'scope': [
            'Data encryption standards',
            'Access control policies',
            'Incident response procedures',
            'Backup and recovery systems'
        ],
        'findings': [
            {
                'area': 'Data Encryption',
                'status': 'Compliant',
                'severity': 'Low',
                'description': 'All data at rest and in transit is properly encrypted using industry standards.'
            },
            {
                'area': 'Access Controls',
                'status': 'Needs Review',
                'severity': 'Medium',
                'description': 'Some service accounts have broader permissions than required.'
            }
        ],
        'compliance_score': 87,
        'recommendations': [
            {'priority': 'High', 'text': 'Implement least-privilege access for service accounts'},
            {'priority': 'Medium', 'text': 'Review and update incident response playbook'},
            {'priority': 'Low', 'text': 'Schedule quarterly security training'}
        ]
    }
    
    result = report_generator.generate_audit_report(audit_data)
    print(f"Audit report generated: {result.report_id}")
    
    print("\nAll reports saved to: data/reports/")
